try{
    console.log("hello");
    console.log(x);
    console.log("ends here");
}
catch(err){
    console.log("I am inside catch block");
    console.log("Your error is here: ",err);
} 